### ISSUE TITLE
[Feat] 라우터 관리 객체 구성

### ISSUE THREAD

**Issue by jjh4450** [kakao-tech-campus-2nd-step3/Team2_FE#12]
현재 라우팅과 관련해서 하드코딩의 여지가 있는 부분이 많이 보입니다. 라우터 기능은 매우 자주 사용, 변경되는 만큼 중앙화를 위해 별도의 관리용 객체 사용 논의가 필요할거 같습니다.

**Comment by dandamdandam** [comment]
path.ts 로 구현해두긴했었는데, 추가를 염두해서 객체 하나로 만들어보겠습니다.

이번에 바꾸기에는 작업이 진행중이라, 다음주에 적용해둘께요!
