### ISSUE TITLE
[FIX] Article api 관련 건의

### ISSUE THREAD

**Issue by youcastle03** [kakao-tech-campus-2nd-step3/Team2_FE#52]
![image](https://github.com/user-attachments/assets/aabb7cca-cfec-42bd-81d2-417c73eaa52d)
/api/article Post로 칼럼을 생성할때 id를 requierd로 받고 있는데 컬럼id는 생성시에 백엔드에서 자동으로 생성 해주므로 필요가 없는 속성이라 생각하는데 삭제를 해도 될까요?? 확인 부탁드립니다!!

**Comment by humpose** [comment]
네 이부분은 제가 삭제하도록 하겠습니다. 실제 로직에서도 생성할때 정합성을 이유로 id를 받지 않고 있습니다. api문서 작업할때 실수가 있었네요!!

**Comment by youcastle03** [comment]
프론트 분들이 확인하시면 issue close해주세요!
