### ISSUE TITLE
리펙터링 교통 정리용 이슈란

### ISSUE THREAD

**Issue by jjh4450** [kakao-tech-campus-2nd-step3/Team2_FE#81]
리펙터링 교통 정리용 이슈란
> (리팩터링은 자율이며, 12/3일 이후 진행될 예정입니다.)

- 조직 옮길거여? @dandamdandam

**Comment by dandamdandam** [comment]
이슈랑 PR이 모여 있었으면 좋겠어서 여기서 하려고

**Comment by jjh4450** [comment]
버셀 불편하지 않아?
